#
# tghistory config file
#

telegram:
  path: /Users/nshahzad/source/tg/bin/telegram-cli
  pubkey: ~/.ssh/telegram.pub
  batch_read_count: 1000

pelican:
  bin: env/bin/pelican
  config: pelicanconfig.py
  working_dir: tmp/
  output_dir: output/

